<!-- Generated by MockUp Builder |  (MemberList) | route: /generated/member-list | 2026-04-20T09:01:29.055Z -->
<template>
<!--
  @id: page-split-container
  @type: container
  @summary: 메인/사이드 분할
  @note: 화면을 2영역으로 분리
  @model: null
  @constraints: null
-->
  <StandardListTemplate>

    <template #title>
      <h2 class="gp-page-title"></h2>
    </template>

    <template #actions-right>
      <!--
        @id: excel-download-button
        @type: action
        @summary: 엑셀 다운로드
        @note: 목록 엑셀 저장
        @model: null
        @constraints: null
      -->
      <button class="gp-btn gp-btn--primary" @click="() => {}">등록</button>
      <button class="gp-btn gp-btn--outline" @click="() => {}">엑셀 다운로드</button>
      <button class="gp-btn gp-btn--outline" @click="() => {}">상세</button>
      <button class="gp-btn gp-btn--danger"  @click="() => {}">삭제</button>
    </template>

    <template #default>
      <div class="gp-table-wrap">
        <!--
          @id: member-list-table
          @type: display
          @summary: 회원 목록 테이블
          @note: pagedRows 목록 표시
          @model: null
          @constraints: null
        -->
        <table class="gp-table">
          <thead>
            <tr>
              <th class="gp-th" style="width:50px">No</th>

            </tr>
          </thead>
          <tbody>
            <!--
              @id: empty-result-row
              @type: display
              @summary: 빈 결과 안내
              @note: 데이터 없으면 문구 노출
              @model: null
              @constraints: pagedRows.length가 0일 때만 표시
            -->
            <tr v-if="!pagedRows.length">
              <td :colspan="1" class="gp-td gp-td--empty">조회 결과가 없습니다.</td>
            </tr>
            <!--
              @id: paged-row-item
              @type: display
              @summary: 목록 행
              @note: 페이지 행 반복 출력
              @model: null
              @constraints: pagedRows 배열 기준 반복
            -->
            <tr v-for="(row, i) in pagedRows" :key="i" class="gp-tr">
              <td class="gp-td">{{ (page - 1) * PAGE_SIZE + i + 1 }}</td>

            </tr>
          </tbody>
        </table>
      </div>
    </template>

    <template #pagination>
      <div class="gp-pagination">
        <button class="gp-btn gp-btn--outline" :disabled="page <= 1" @click="page--">이전</button>
        <!--
          @id: pagination-info
          @type: display
          @summary: 페이지 정보
          @note: 현재/전체/총건수 표시
          @model: null
          @constraints: null
        -->
        <span class="gp-pagination__info">{{ page }} / {{ totalPages }} (총 {{ filteredRows.length }}건)</span>
        <button class="gp-btn gp-btn--outline" :disabled="page >= totalPages" @click="page++">다음</button>
      </div>
    </template>

  </StandardListTemplate>

</template>

<script lang="ts" setup>
/* [interview-result:start] */
/**
 * @screen: MemberList
 * @generatedAt: 2026-04-20T09:03:25.767Z
 * @pipeline: interview-result-v1
 *
 */
/* [interview-result:end] */
import { ref, computed, reactive } from 'vue';
import { StandardListTemplate } from '@/components/templates';

const PAGE_SIZE = 10;
const page = ref(1);

const search = reactive<Record<string, string>>({

});

const MOCK_DATA: Record<string, string>[] = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
];

const filteredRows = computed(() =>
  MOCK_DATA.filter(row =>
    true
  ),
);

const totalPages = computed(() =>
  Math.max(1, Math.ceil(filteredRows.value.length / PAGE_SIZE)),
);

const pagedRows = computed(() =>
  filteredRows.value.slice((page.value - 1) * PAGE_SIZE, page.value * PAGE_SIZE),
);

function onSearch() {
  page.value = 1;
}

function onReset() {

  page.value = 1;
}
</script>

<style scoped>
.gp-page-title {
  font-size: 18px;
  font-weight: 700;
  color: var(--txt-color-1);
  margin: 0;
}

/* ── 검색 바 ── */
.gp-search-bar {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  gap: 12px;
  padding: 14px 16px;
  background: var(--bg-2);
  border: 1px solid var(--divider-1);
  border-radius: 6px;
}

.gp-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.gp-label {
  font-size: 11px;
  font-weight: 500;
  color: var(--txt-color-3);
}

.gp-search-actions {
  display: flex;
  gap: 6px;
  padding-top: 14px;
}

.gp-field--inline {
  flex-direction: row;
  align-items: center;
  padding-top: 18px;
  gap: 6px;
}

.gp-date-range {
  display: flex;
  align-items: center;
  gap: 6px;
}

.gp-date-sep {
  color: var(--txt-color-3);
  font-size: 13px;
}

.gp-input--date {
  min-width: 120px;
  max-width: 140px;
}

.gp-label--cb {
  padding-top: 0;
  font-size: 13px;
  color: var(--txt-color-1);
  cursor: pointer;
}

.gp-checkbox {
  width: 15px;
  height: 15px;
  cursor: pointer;
  accent-color: var(--brand-secondary-color);
}

.gp-input,
.gp-select {
  height: 32px;
  padding: 0 10px;
  border: 1px solid var(--divider-2);
  border-radius: 4px;
  font-size: 13px;
  background: var(--bg-1);
  color: var(--txt-color-1);
  outline: none;
  min-width: 140px;
}
.gp-input:focus,
.gp-select:focus {
  border-color: var(--brand-secondary-color);
}

/* ── 버튼 ── */
.gp-btn {
  height: 32px;
  padding: 0 14px;
  border-radius: 4px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: 1px solid transparent;
  transition: opacity 0.15s;
}
.gp-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.gp-btn--primary { background: var(--brand-secondary-color); color: #fff; border-color: var(--brand-secondary-color); }
.gp-btn--outline { background: var(--bg-1); border-color: var(--divider-2); color: var(--txt-color-2); }
.gp-btn--danger  { background: #ef4444; color: #fff; border-color: #ef4444; }

/* ── 테이블 ── */
.gp-table-wrap {
  width: 100%;
  height: 100%;
  overflow: auto;
}

.gp-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.gp-th {
  background: var(--bg-2);
  color: var(--txt-color-2);
  font-weight: 600;
  text-align: left;
  padding: 10px 12px;
  border-bottom: 2px solid var(--divider-2);
  white-space: nowrap;
  position: sticky;
  top: 0;
  z-index: 1;
}

.gp-td {
  padding: 9px 12px;
  border-bottom: 1px solid var(--divider-1);
  color: var(--txt-color-1);
}
.gp-td--empty {
  text-align: center;
  color: var(--txt-color-4);
  padding: 48px 0;
}

.gp-tr:hover { background: var(--bg-2); }

/* ── 페이지네이션 ── */
.gp-pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 14px;
  padding: 8px 0;
}

.gp-pagination__info {
  font-size: 13px;
  color: var(--txt-color-3);
}

</style>
