<!-- Generated by MockUp Builder | 회원 목록 (MemberList) | route: /generated/member-list | 2026-04-20T12:11:29.346Z -->
<template>
<!--
  @id: page-split-layout
  @type: container
  @summary: 메인·사이드 분할
  @note: 목록과 인터뷰 영역 분리
  @model: null
  @constraints: null
-->
  <StandardListTemplate>

    <template #title>
      <!--
        @id: member-list-title
        @type: display
        @summary: 회원 목록 제목
        @note: 리스트 화면 제목 표시
        @model: null
        @constraints: null
      -->
      <h2 class="gp-page-title">회원 목록</h2>
    </template>

    <template #search>
      <!--
        @id: member-search-bar
        @type: container
        @summary: 회원 검색 영역
        @note: 조건 입력과 검색 실행
        @model: null
        @constraints: null
      -->
      <div class="gp-search-bar">
        <div class="gp-field">
          <label class="gp-label">회원명</label>
          <!--
            @id: search-member-name
            @type: input
            @summary: 회원명 검색어
            @note: 회원명 텍스트 입력
            @model: search.memberName
            @constraints: null
          -->
          <input v-model="search.memberName" type="text" class="gp-input" placeholder="회원명" />
        </div>
        <div class="gp-field">
          <label class="gp-label">로그인ID</label>
          <input v-model="search.loginId" type="text" class="gp-input" placeholder="로그인ID" />
        </div>
        <div class="gp-field">
          <label class="gp-label">회원상태</label>
          <!--
            @id: search-member-status
            @type: input
            @summary: 회원상태 선택
            @note: 전체·정상·휴면·탈퇴 선택
            @model: search.memberStatus
            @constraints: 값은 '', ACTIVE, DORMANT, WITHDRAWN
          -->
          <select v-model="search.memberStatus" class="gp-select">
            <option value="">전체</option>
              <option value="ACTIVE">정상</option>
              <option value="DORMANT">휴면</option>
              <option value="WITHDRAWN">탈퇴</option>
          </select>
        </div>
        <div class="gp-field">
          <label class="gp-label">가입일</label>
          <div class="gp-date-range">
            <input v-model="search.joinDateFrom" type="date" class="gp-input gp-input--date" />
            <span class="gp-date-sep">~</span>
            <input v-model="search.joinDateTo" type="date" class="gp-input gp-input--date" />
          </div>
        </div>
        <div class="gp-field gp-field--inline">
          <input v-model="search.emailVerifiedYn" type="checkbox" id="sch_emailVerifiedYn" class="gp-checkbox" />
          <label class="gp-label gp-label--cb" for="sch_emailVerifiedYn">이메일인증여부</label>
        </div>
        <div class="gp-search-actions">
          <!--
            @id: search-submit
            @type: action
            @summary: 조회 버튼
            @note: onSearch 실행
            @model: null
            @constraints: null
          -->
          <button class="gp-btn gp-btn--primary" @click="onSearch">조회</button>
          <button class="gp-btn gp-btn--outline" @click="onReset">초기화</button>
        </div>
      </div>
    </template>

    <template #actions-right>
      <button class="gp-btn gp-btn--primary" @click="() => {}">등록</button>
      <button class="gp-btn gp-btn--outline" @click="() => {}">엑셀 다운로드</button>
      <button class="gp-btn gp-btn--outline" @click="() => {}">상세</button>
      <button class="gp-btn gp-btn--danger"  @click="() => {}">삭제</button>
    </template>

    <template #default>
      <div class="gp-table-wrap">
        <!--
          @id: member-list-table
          @type: display
          @summary: 회원 목록 테이블
          @note: 페이지 목록 데이터 표시
          @model: null
          @constraints: 컬럼 8개, 결과 없으면 빈행 표시
        -->
        <table class="gp-table">
          <thead>
            <tr>
              <th class="gp-th" style="width:50px">No</th>
              <th class="gp-th">회원번호</th>
              <th class="gp-th">회원명</th>
              <th class="gp-th">로그인ID</th>
              <th class="gp-th">휴대폰번호</th>
              <th class="gp-th">회원상태</th>
              <th class="gp-th">이메일인증</th>
              <th class="gp-th">가입일</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="!pagedRows.length">
              <td :colspan="8" class="gp-td gp-td--empty">조회 결과가 없습니다.</td>
            </tr>
            <tr v-for="(row, i) in pagedRows" :key="i" class="gp-tr">
              <td class="gp-td">{{ (page - 1) * PAGE_SIZE + i + 1 }}</td>
              <td class="gp-td">{{ row.memberNo }}</td>
              <td class="gp-td">{{ row.memberName }}</td>
              <td class="gp-td">{{ row.loginId }}</td>
              <td class="gp-td">{{ row.mobileNo }}</td>
              <td class="gp-td">{{ row.memberStatus }}</td>
              <td class="gp-td">{{ row.emailVerifiedYn }}</td>
              <td class="gp-td">{{ row.joinDate }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>

    <template #pagination>
      <div class="gp-pagination">
        <button class="gp-btn gp-btn--outline" :disabled="page <= 1" @click="page--">이전</button>
        <span class="gp-pagination__info">{{ page }} / {{ totalPages }} (총 {{ filteredRows.length }}건)</span>
        <button class="gp-btn gp-btn--outline" :disabled="page >= totalPages" @click="page++">다음</button>
      </div>
    </template>

  </StandardListTemplate>

</template>

<script lang="ts" setup>
/* [interview-result:start] */
/**
 * @screen: MemberList
 * @generatedAt: 2026-04-20T12:13:59.027Z
 * @pipeline: interview-result-v1
 *
 */
/* [interview-result:end] */
import { ref, computed, reactive } from 'vue';
import { StandardListTemplate } from '@/components/templates';

const PAGE_SIZE = 10;
const page = ref(1);

const search = reactive<Record<string, string | boolean>>({
  memberName: '',
  loginId: '',
  memberStatus: '',
  joinDateFrom: '',
  joinDateTo: '',
  emailVerifiedYn: false
});

const MOCK_DATA: Record<string, string>[] = [
  {
    "memberNo": "100001",
    "memberName": "김민수",
    "loginId": "minsu.kim",
    "mobileNo": "010-2345-6789",
    "memberStatus": "ACTIVE",
    "emailVerifiedYn": "Y",
    "joinDate": "2025-01-15"
  },
  {
    "memberNo": "100002",
    "memberName": "이서연",
    "loginId": "seoyeon.lee",
    "mobileNo": "010-3456-7890",
    "memberStatus": "ACTIVE",
    "emailVerifiedYn": "Y",
    "joinDate": "2025-01-18"
  },
  {
    "memberNo": "100003",
    "memberName": "박지훈",
    "loginId": "jihoon.park",
    "mobileNo": "010-4567-8901",
    "memberStatus": "DORMANT",
    "emailVerifiedYn": "N",
    "joinDate": "2025-02-03"
  },
  {
    "memberNo": "100004",
    "memberName": "최유진",
    "loginId": "yujin.choi",
    "mobileNo": "010-5678-9012",
    "memberStatus": "ACTIVE",
    "emailVerifiedYn": "Y",
    "joinDate": "2025-02-11"
  },
  {
    "memberNo": "100005",
    "memberName": "정현우",
    "loginId": "hyunwoo.jung",
    "mobileNo": "010-6789-0123",
    "memberStatus": "WITHDRAWN",
    "emailVerifiedYn": "N",
    "joinDate": "2025-02-20"
  },
  {
    "memberNo": "100006",
    "memberName": "한지민",
    "loginId": "jimin.han",
    "mobileNo": "010-7890-1234",
    "memberStatus": "ACTIVE",
    "emailVerifiedYn": "Y",
    "joinDate": "2025-03-05"
  },
  {
    "memberNo": "100007",
    "memberName": "오세훈",
    "loginId": "sehun.oh",
    "mobileNo": "010-8901-2345",
    "memberStatus": "DORMANT",
    "emailVerifiedYn": "Y",
    "joinDate": "2025-03-14"
  },
  {
    "memberNo": "100008",
    "memberName": "윤아름",
    "loginId": "areum.yoon",
    "mobileNo": "010-9012-3456",
    "memberStatus": "ACTIVE",
    "emailVerifiedYn": "N",
    "joinDate": "2025-03-22"
  },
  {
    "memberNo": "100009",
    "memberName": "강도윤",
    "loginId": "doyoon.kang",
    "mobileNo": "010-1122-3344",
    "memberStatus": "ACTIVE",
    "emailVerifiedYn": "Y",
    "joinDate": "2025-04-02"
  },
  {
    "memberNo": "100010",
    "memberName": "신가은",
    "loginId": "gaeun.shin",
    "mobileNo": "010-2233-4455",
    "memberStatus": "WITHDRAWN",
    "emailVerifiedYn": "N",
    "joinDate": "2025-04-10"
  }
];

const filteredRows = computed(() =>
  MOCK_DATA.filter(row =>
    (!search.memberName || String(row.memberName ?? '').includes(String(search.memberName))) &&
    (!search.loginId || String(row.loginId ?? '').includes(String(search.loginId))) &&
    (!search.memberStatus || String(row.memberStatus ?? '').includes(String(search.memberStatus))) &&
    (!search.joinDateFrom || String(row.joinDate ?? '') >= String(search.joinDateFrom)) &&
    (!search.joinDateTo   || String(row.joinDate ?? '') <= String(search.joinDateTo)) &&
    (!search.emailVerifiedYn || String(row.emailVerifiedYn ?? '') === 'true')
  ),
);

const totalPages = computed(() =>
  Math.max(1, Math.ceil(filteredRows.value.length / PAGE_SIZE)),
);

const pagedRows = computed(() =>
  filteredRows.value.slice((page.value - 1) * PAGE_SIZE, page.value * PAGE_SIZE),
);

function onSearch() {
  page.value = 1;
}

function onReset() {
  search.memberName = '';
  search.loginId = '';
  search.memberStatus = '';
  search.joinDateFrom = '';
  search.joinDateTo = '';
  search.emailVerifiedYn = false;
  page.value = 1;
}
</script>

<style scoped>
.gp-page-title {
  font-size: 18px;
  font-weight: 700;
  color: var(--txt-color-1);
  margin: 0;
}

/* ── 검색 바 ── */
.gp-search-bar {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  gap: 12px;
  padding: 14px 16px;
  background: var(--bg-2);
  border: 1px solid var(--divider-1);
  border-radius: 6px;
}

.gp-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.gp-label {
  font-size: 11px;
  font-weight: 500;
  color: var(--txt-color-3);
}

.gp-search-actions {
  display: flex;
  gap: 6px;
  padding-top: 14px;
}

.gp-field--inline {
  flex-direction: row;
  align-items: center;
  padding-top: 18px;
  gap: 6px;
}

.gp-date-range {
  display: flex;
  align-items: center;
  gap: 6px;
}

.gp-date-sep {
  color: var(--txt-color-3);
  font-size: 13px;
}

.gp-input--date {
  min-width: 120px;
  max-width: 140px;
}

.gp-label--cb {
  padding-top: 0;
  font-size: 13px;
  color: var(--txt-color-1);
  cursor: pointer;
}

.gp-checkbox {
  width: 15px;
  height: 15px;
  cursor: pointer;
  accent-color: var(--brand-secondary-color);
}

.gp-input,
.gp-select {
  height: 32px;
  padding: 0 10px;
  border: 1px solid var(--divider-2);
  border-radius: 4px;
  font-size: 13px;
  background: var(--bg-1);
  color: var(--txt-color-1);
  outline: none;
  min-width: 140px;
}
.gp-input:focus,
.gp-select:focus {
  border-color: var(--brand-secondary-color);
}

/* ── 버튼 ── */
.gp-btn {
  height: 32px;
  padding: 0 14px;
  border-radius: 4px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: 1px solid transparent;
  transition: opacity 0.15s;
}
.gp-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.gp-btn--primary { background: var(--brand-secondary-color); color: #fff; border-color: var(--brand-secondary-color); }
.gp-btn--outline { background: var(--bg-1); border-color: var(--divider-2); color: var(--txt-color-2); }
.gp-btn--danger  { background: #ef4444; color: #fff; border-color: #ef4444; }

/* ── 테이블 ── */
.gp-table-wrap {
  width: 100%;
  height: 100%;
  overflow: auto;
}

.gp-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.gp-th {
  background: var(--bg-2);
  color: var(--txt-color-2);
  font-weight: 600;
  text-align: left;
  padding: 10px 12px;
  border-bottom: 2px solid var(--divider-2);
  white-space: nowrap;
  position: sticky;
  top: 0;
  z-index: 1;
}

.gp-td {
  padding: 9px 12px;
  border-bottom: 1px solid var(--divider-1);
  color: var(--txt-color-1);
}
.gp-td--empty {
  text-align: center;
  color: var(--txt-color-4);
  padding: 48px 0;
}

.gp-tr:hover { background: var(--bg-2); }

/* ── 페이지네이션 ── */
.gp-pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 14px;
  padding: 8px 0;
}

.gp-pagination__info {
  font-size: 13px;
  color: var(--txt-color-3);
}

</style>
