<!-- Generated by MockUp Builder | 사용자관리 (UserList) | route: /generated/UserList | 2026-04-10T06:43:16.404Z -->
<!--
=== 고객용 화면 가이드 (LLM) ===
| 위치/컴포넌트 | 비즈니스 로직 및 기술 사양 | 고객 확인 사항 (인터뷰 질문) |
| :--- | :--- | :--- |
| 사용자관리 화면(StandardListTemplate / route: `/generated/UserList`) | [작동] 사용자 목록을 검색조건으로 필터링하여 테이블로 표시하고, 페이지네이션(이전/다음)으로 10건 단위 탐색<br><br>[데이터] 화면 상태: `PAGE_SIZE:number=10`, `page:number(1~totalPages)`<br><br>[API] (목업은 로컬 `MOCK_DATA` 사용) 실제 연동 시 예상: `GET /api/users` (query: keyword, deptName, roleCode, useYn, createdFrom, createdTo, page, size) | [확인] 검색/페이징을 서버에서 처리할지(서버 페이징) 화면에서 처리할지(클라이언트 필터링) 결정 필요<br><br>[예외] API 장애/타임아웃 시 메시지/재시도 정책, 권한없음(401/403) 시 처리(로그인 이동/권한 안내) |
| 통합검색(아이디/이름/이메일) 입력(search.keyword) | [작동] 입력값이 있으면 사용자 목록을 “아이디/이름/이메일”에 대해 부분일치로 검색하는 의도. **단, 현재 코드 버그**: `row.keyword`를 조회하여 실제 데이터(`userId/userName/email`)와 매칭되지 않음 → 항상 미동작 가능<br><br>[데이터] `search.keyword: string` (권장 max 100), 선택값(필수 아님)<br><br>[API] `GET /api/users?keyword={string}` (서버에서 userId/userName/email OR 검색) | [확인] 통합검색 범위가 정확히 3개(userId,userName,email)인지, 추가 필드(전화번호 등) 포함 여부<br><br>[예외] 특수문자/공백만 입력 시 처리(무시/에러), 대소문자 구분 여부 |
| 부서명 입력(search.deptName) | [작동] 부서명 부분일치 필터링<br><br>[데이터] `search.deptName: string` (권장 max 100), 선택값<br><br>[API] `GET /api/users?deptName={string}` | [확인] 부서명은 자유입력(부분일치)인지, 부서코드 기반 선택(드롭다운/조직도)로 바꿀지<br><br>[예외] 존재하지 않는 부서명 입력 시 “0건”만 표시할지, 추천/자동완성 제공할지 |
| 권한 선택(search.roleCode) | [작동] 권한코드로 필터링(전체/ADMIN/MANAGER/USER/AUDITOR)<br><br>[데이터] `search.roleCode: '' \| 'ADMIN' \| 'MANAGER' \| 'USER' \| 'AUDITOR'` 선택값<br><br>[API] `GET /api/users?roleCode={code}`<br>코드마스터(권한): `ROLE_CODE` (예상) | [확인] 권한 체계가 고정 4종인지, 향후 확장/다중권한(한 사용자가 여러 Role) 가능성 여부<br><br>[예외] 알 수 없는 roleCode 수신 시 화면 표기(코드 그대로/“미정”) 규칙 |
| 사용여부 체크박스(사용여부, sch_useYn / search.useYn) | [작동] 체크 시 “사용중 사용자만” 필터링하려는 의도. **단, 현재 코드 버그**: `row.useYn`은 'Y'/'N'인데 비교를 `'true'`로 함 → 체크 시 결과가 0건 될 가능성 큼<br><br>[데이터] `search.useYn: boolean` (기본 false=전체), row의 `useYn: 'Y' \| 'N'`로 정규화 필요<br><br>[API] `GET /api/users?useYn=Y` (권장: boolean 대신 Y/N 또는 true/false 일관화) | [확인] “사용여부” 체크의 의미가 ‘사용=Y만’인지, ‘미사용=N만’도 조회 옵션이 필요한지(라디오/셀렉트로 변경 필요 여부)<br><br>[예외] 휴면/잠금/퇴사 등 상태값이 추가될 경우 useYn만으로 충분한지(STATUS 컬럼 필요) |
| 등록일 기간 From(search.createdDateRangeFrom) | [작동] 등록일 시작일 조건(이상) 필터링 의도. **단, 현재 코드 버그**: `row.createdDateRange` 필드가 없고 실제는 `createdDate`임 → 미동작 가능<br><br>[데이터] `search.createdDateRangeFrom: string(date, 'YYYY-MM-DD')` 선택값<br><br>[API] `GET /api/users?createdFrom=YYYY-MM-DD` | [확인] 등록일 기준이 “계정 생성일”인지 “최초 승인일/가입일”인지 정의 필요<br><br>[예외] From만 입력 시 허용 여부, 타임존/일자 경계(00:00~23:59) 처리 기준 |
| 등록일 기간 To(search.createdDateRangeTo) | [작동] 등록일 종료일 조건(이하) 필터링 의도. **단, 현재 코드 버그**: 위와 동일(`createdDateRange` 미존재)<br><br>[데이터] `search.createdDateRangeTo: string(date, 'YYYY-MM-DD')` 선택값<br><br>[API] `GET /api/users?createdTo=YYYY-MM-DD` | [확인] To 날짜 포함 여부(포함/미포함). 일반적으로 포함(<=) 처리하되 서버에서 `23:59:59` 보정 필요 여부<br><br>[예외] From > To 입력 시 즉시 검증(클라이언트)할지, 서버에서 400으로 반환할지 |
| 조회 버튼(@click="onSearch") | [작동] 현재 페이지를 1로 리셋하여 필터 결과 첫 페이지로 이동(실제 데이터 재조회는 없음: 목업은 computed 필터링)<br><br>[데이터] `page=1`로 변경<br><br>[API] (서버형) `GET /api/users` 재호출 트리거. 파라미터: search 조건 + `page=1&size=10` | [확인] 조회는 버튼 클릭 시에만 수행할지, 입력 즉시 자동조회(디바운스)도 원하는지<br><br>[예외] 조회 중 로딩 표시/버튼 비활성화 필요 여부 |
| 초기화 버튼(@click="onReset") | [작동] 검색조건 전체 초기화 + page=1로 리셋<br><br>[데이터] `search.*` 기본값으로 복원, `page=1`<br><br>[API] (서버형) 초기화 후 전체목록 재조회: `GET /api/users?page=1&size=10` | [확인] 초기화 시 기본 필터(예: 사용중만 기본) 적용 여부<br><br>[예외] 초기화 확인 팝업 필요 여부(조건 많이 입력했을 때) |
| 목록 테이블(사용자 리스트) | [작동] `pagedRows`를 행으로 렌더링. 컬럼: No(순번), 사용자ID, 사용자명, 부서, 이메일, 권한, 사용여부, 최종로그인일, 등록일. 결과 없으면 “조회 결과가 없습니다.” 표시<br><br>[데이터] Row 스키마(현재 목업):<br>- `userId: string` (PK 후보, max 50)<br>- `userName: string` (max 100)<br>- `deptName: string` (max 100)<br>- `email: string` (max 254)<br>- `roleCode: string` (코드)<br>- `useYn: 'Y'|'N'`<br>- `lastLoginDate: string(date)` nullable 가능<br>- `createdDate: string(date)`<br><br>[API] (서버형) 응답 예: `{ items: User[], total: number, page: number, size: number }` | [확인] 테이블 행 클릭 시 상세/수정 화면 이동이 필요한지(현재는 단순 표시만 존재)<br><br>[예외] lastLoginDate가 없는 사용자(미로그인) 표기 규칙(빈값/“-”/“미접속”) |
| 페이지네이션: 이전 버튼(@click="page--") | [작동] `page>1`일 때만 이전 페이지로 이동(버튼 disabled 처리)<br><br>[데이터] `page: number` 감소, 하한 1<br><br>[API] (서버형) `GET /api/users?page={page-1}&size=10` | [확인] 페이지 이동 시 스크롤을 상단으로 올릴지 여부<br><br>[예외] totalPages 변경(검색조건 변경)으로 현재 page가 범위를 벗어날 때 보정 규칙(자동 1로 이동 등) |
| 페이지네이션: 다음 버튼(@click="page++") | [작동] `page<totalPages`일 때만 다음 페이지로 이동(버튼 disabled 처리)<br><br>[데이터] `page: number` 증가, 상한 totalPages<br><br>[API] (서버형) `GET /api/users?page={page+1}&size=10` | [확인] 페이지 크기(10) 변경 옵션(20/50/100) 제공 필요 여부<br><br>[예외] 마지막 페이지에서 데이터가 삭제되어 빈 페이지가 될 경우 처리(이전 페이지로 이동 등) |
| 필터링 로직(filteredRows computed) | [작동] 검색조건별 AND 필터링. **현재 코드상 결함/불일치**:<br>1) 통합검색: `row.keyword` 사용(실데이터 필드 없음)<br>2) 사용여부: `row.useYn === 'true'` 비교(Y/N과 불일치)<br>3) 등록일: `row.createdDateRange` 사용(실데이터 필드 없음, 실제는 createdDate)<br><br>[데이터] 필터 대상 필드 정규화 필요: `createdDate`, `useYn` 등<br><br>[API] (권장) 서버에서 동일 조건으로 조회되도록 쿼리 스펙 확정 필요 | [확인] 검색조건은 모두 AND가 맞는지(예: 통합검색은 OR, 나머지는 AND) 확인 필요<br><br>[예외] 날짜 비교는 문자열 비교가 아닌 Date 비교로 처리할지(서버/클라이언트 일관성) |
| DB 스키마 제안: 사용자(USER) | [작동] 화면 표시/검색을 위한 최소 사용자 마스터 테이블(또는 뷰) 필요<br><br>[데이터] (제안) `USER`<br>- `user_id VARCHAR(50) PK NOT NULL`<br>- `user_name VARCHAR(100) NOT NULL`<br>- `dept_id VARCHAR(20) NULL` (또는 dept_name VARCHAR(100))<br>- `email VARCHAR(254) NOT NULL UNIQUE`<br>- `role_code VARCHAR(20) NOT NULL` (FK to ROLE_CODE)<br>- `use_yn CHAR(1) NOT NULL DEFAULT 'Y'`<br>- `last_login_at DATETIME NULL`<br>- `created_at DATETIME NOT NULL`<br>인덱스: (user_id), (email), (dept_id), (role_code), (use_yn), (created_at)<br><br>[API] CRUD 확장 시: `GET/POST/PUT /api/users`, `PATCH /api/users/{id}/useYn` 등 | [확인] 사용자ID 정책(사번/영문아이디)과 중복 허용 여부, 이메일 유니크 여부<br><br>[예외] 개인정보 마스킹(이메일 일부 마스킹) 필요 여부 및 권한별 노출 정책 |
-->

<template>
  <div class="gp-page-split">
    <div class="gp-page-split__main">
  <StandardListTemplate>

    <template #title>
      <h2 class="gp-page-title">사용자관리</h2>
    </template>

    <template #search>
      <div class="gp-search-bar">
        <div class="gp-field">
          <label class="gp-label">통합검색(아이디/이름/이메일)</label>
          <input v-model="search.keyword" type="text" class="gp-input" placeholder="통합검색(아이디/이름/이메일)" />
        </div>
        <div class="gp-field">
          <label class="gp-label">부서명</label>
          <input v-model="search.deptName" type="text" class="gp-input" placeholder="부서명" />
        </div>
        <div class="gp-field">
          <label class="gp-label">권한</label>
          <select v-model="search.roleCode" class="gp-select">
            <option value="">전체</option>
              <option value="ADMIN">관리자</option>
              <option value="MANAGER">매니저</option>
              <option value="USER">일반사용자</option>
              <option value="AUDITOR">감사</option>
          </select>
        </div>
        <div class="gp-field gp-field--inline">
          <input v-model="search.useYn" type="checkbox" id="sch_useYn" class="gp-checkbox" />
          <label class="gp-label gp-label--cb" for="sch_useYn">사용여부</label>
        </div>
        <div class="gp-field">
          <label class="gp-label">등록일</label>
          <div class="gp-date-range">
            <input v-model="search.createdDateRangeFrom" type="date" class="gp-input gp-input--date" />
            <span class="gp-date-sep">~</span>
            <input v-model="search.createdDateRangeTo" type="date" class="gp-input gp-input--date" />
          </div>
        </div>
        <div class="gp-search-actions">
          <button class="gp-btn gp-btn--primary" @click="onSearch">조회</button>
          <button class="gp-btn gp-btn--outline" @click="onReset">초기화</button>
        </div>
      </div>
    </template>

    <template #default>
      <div class="gp-table-wrap">
        <table class="gp-table">
          <thead>
            <tr>
              <th class="gp-th" style="width:50px">No</th>
              <th class="gp-th">사용자ID</th>
              <th class="gp-th">사용자명</th>
              <th class="gp-th">부서</th>
              <th class="gp-th">이메일</th>
              <th class="gp-th">권한</th>
              <th class="gp-th">사용여부</th>
              <th class="gp-th">최종로그인일</th>
              <th class="gp-th">등록일</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="!pagedRows.length">
              <td :colspan="9" class="gp-td gp-td--empty">조회 결과가 없습니다.</td>
            </tr>
            <tr v-for="(row, i) in pagedRows" :key="i" class="gp-tr">
              <td class="gp-td">{{ (page - 1) * PAGE_SIZE + i + 1 }}</td>
              <td class="gp-td">{{ row.userId }}</td>
              <td class="gp-td">{{ row.userName }}</td>
              <td class="gp-td">{{ row.deptName }}</td>
              <td class="gp-td">{{ row.email }}</td>
              <td class="gp-td">{{ row.roleCode }}</td>
              <td class="gp-td">{{ row.useYn }}</td>
              <td class="gp-td">{{ row.lastLoginDate }}</td>
              <td class="gp-td">{{ row.createdDate }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>

    <template #pagination>
      <div class="gp-pagination">
        <button class="gp-btn gp-btn--outline" :disabled="page <= 1" @click="page--">이전</button>
        <span class="gp-pagination__info">{{ page }} / {{ totalPages }} (총 {{ filteredRows.length }}건)</span>
        <button class="gp-btn gp-btn--outline" :disabled="page >= totalPages" @click="page++">다음</button>
      </div>
    </template>

  </StandardListTemplate>
    </div>
    <aside class="gp-page-split__side" aria-label="요구사항 인터뷰 질문지">
      <div class="gp-side-header">
        <h3 class="gp-side-title">요구사항 인터뷰 질문지</h3>
        <div class="gp-side-header-actions">
          <button class="gp-side-add-btn" @click="addQA">+ 질문 추가</button>
          <button class="gp-side-copy-btn" :class="{ 'gp-side-copy-btn--done': answerCopied }" @click="copyAnswers">
            {{ answerCopied ? '복사됨!' : '전체 복사' }}
          </button>
        </div>
      </div>
      <ol class="gp-side-list">
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">사용자 목록 조회는 서버 페이징/필터링(권장: GET /api/users)으로 처리할까요, 아니면 전체 데이터를 내려받아 클라이언트에서 필터링할까요? 서버 처리라면 응답 스펙을 {items, total, page, size}로 확정해도 되는지와, total은 '필터 적용 후 전체 건수' 기준이 맞는지도 확인 부탁드립니다.</p>
        <textarea v-model="answers[0]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">통합검색(keyword)의 검색 대상 필드를 userId/userName/email 3개로 확정할까요, 아니면 전화번호/사번 등 추가 필드도 포함해야 할까요? 또한 매칭 방식은 부분일치(contains/LIKE)로 할지, 시작일치(prefix) 또는 정확일치(equal) 옵션이 필요한지도 결정이 필요합니다(대소문자 구분/공백·특수문자만 입력 시 처리 규칙 포함).</p>
        <textarea v-model="answers[1]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">부서 조건은 현재처럼 '부서명 자유입력 + 부분일치'로 갈까요, 아니면 조직도/부서코드 기반 선택(드롭다운/자동완성)으로 변경이 필요할까요? 코드 기반이라면 조회 파라미터를 deptId로 받을지, deptPath(상위 포함) 검색이 필요한지도 함께 확인 부탁드립니다.</p>
        <textarea v-model="answers[2]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">데이터정의</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">사용자 목록 Row 스키마를 확정해야 합니다: userId(VARCHAR 길이/허용문자/중복정책), userName(최대길이/필수), email(필수 여부/UNIQUE 여부/형식검증), dept는 deptId FK로 저장할지 deptName을 직접 저장할지, roleCode 길이/코드마스터 연동 여부를 각각 확정해 주실 수 있을까요? 또한 lastLoginDate/createdDate는 DATE로 충분한지, DATETIME(타임존 포함)까지 필요한지도 결정이 필요합니다.</p>
        <textarea v-model="answers[3]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">권한(roleCode)은 현재 4종(ADMIN/MANAGER/USER/AUDITOR) 단일값으로 고정할까요, 아니면 향후 한 사용자가 여러 권한을 가질 수 있는 다중권한(매핑 테이블)까지 고려해야 할까요? 다중권한이라면 목록 표시는 '대표권한 1개'인지 '복수 표기'인지, 검색은 AND/OR 중 어떤 방식인지도 확정이 필요합니다.</p>
        <textarea v-model="answers[4]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">사용여부(useYn) 조회 UX를 확정해야 합니다. 현재 체크박스는 '체크 시 사용중(Y)만' 의도인데, 미사용(N)만 조회하거나 '전체/사용/미사용' 3상태 선택이 필요할까요? 또한 휴면/잠금/퇴사 등 상태가 추가될 가능성이 있다면 useYn 대신 status 코드(예: ACTIVE/DORMANT/LOCKED/RESIGNED)로 확장하는 것이 필요한지 확인 부탁드립니다.</p>
        <textarea v-model="answers[5]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">등록일(createdFrom/createdTo) 기준일을 '계정 생성일(created_at)'로 볼지, '최초 승인일/가입완료일' 등 다른 업무 기준일이 있는지 확정이 필요합니다. 또한 From만/To만 입력을 허용할지, To는 포함(&lt;=) 처리할지(서버에서 23:59:59 보정 여부), 타임존 기준(UTC vs KST)도 함께 결정 부탁드립니다.</p>
        <textarea v-model="answers[6]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">조회조건</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">목록의 기본 정렬 기준을 무엇으로 할까요(예: created_at DESC, userId ASC 등)? 또한 컬럼 헤더 클릭 정렬(멀티정렬 포함) 요구가 있는지, 정렬이 필요하다면 API 파라미터(sort=createdAt,desc 등) 규격을 어떻게 가져갈지도 확정이 필요합니다.</p>
        <textarea v-model="answers[7]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">사용자행동</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">테이블 행 클릭/사용자ID 클릭 시 '상세조회/수정' 화면으로 이동이 필요한가요, 아니면 현 화면은 조회 전용인가요? 이동이 필요하다면 라우팅(/users/{userId}) 및 필요한 추가 API(상세 GET, 수정 PUT/PATCH, 사용여부 토글 PATCH 등) 범위를 어디까지로 할지 결정 부탁드립니다.</p>
        <textarea v-model="answers[8]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      <li class="gp-side-item">
        <div class="gp-side-meta"><span class="gp-side-cat">예외처리</span><span class="gp-side-pri gp-side-pri--mid">보통</span></div>
        <p class="gp-side-q">API 오류/권한 오류/데이터 없음에 대한 UX 정책을 확정해야 합니다. 예를 들어 401은 로그인 화면으로 이동할지, 403은 '권한 없음' 안내만 할지, 5xx/타임아웃은 재시도 버튼 제공 여부와 메시지 문구/로깅(에러코드 노출 여부)을 어떻게 할까요? 또한 조회 중 로딩 표시와 버튼 비활성화(중복요청 방지)도 필요한지 확인 부탁드립니다.</p>
        <textarea v-model="answers[9]" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
      </li>
      </ol>
      <div v-if="customQAs.length" class="gp-side-custom">
        <div class="gp-side-custom-divider">현장 추가 질문</div>
        <ol class="gp-side-list gp-side-list--custom">
          <li v-for="(item, i) in customQAs" :key="i" class="gp-side-item gp-side-item--custom">
            <div class="gp-side-custom-q-row">
              <input v-model="item.question" class="gp-side-custom-q-input" placeholder="질문을 입력하세요..." />
              <button class="gp-side-del-btn" title="삭제" @click="removeQA(i)">✕</button>
            </div>
            <textarea v-model="item.answer" class="gp-side-answer" placeholder="답변을 입력하세요..." rows="3" />
          </li>
        </ol>
      </div>
      <div v-else class="gp-side-custom-empty">
        <button class="gp-side-add-btn gp-side-add-btn--ghost" @click="addQA">+ 현장 질문 추가</button>
      </div>

      <!-- 인터뷰결과생성 -->
      <div class="gp-side-result-area">
        <div v-if="resultStatus === 'success'" class="gp-side-result-msg gp-side-result-msg--ok">
          ✓ InterviewNote.md 생성 완료<br>
          <small>src/spec-source/UserList/</small>
        </div>
        <div v-else-if="resultStatus === 'error'" class="gp-side-result-msg gp-side-result-msg--err">
          {{ resultMessage }}
        </div>
        <button
          class="gp-side-generate-btn"
          :class="{ 'gp-side-generate-btn--ready': interviewCompleted }"
          :disabled="resultGenerating || !interviewCompleted"
          @click="generateInterviewResult"
        >
          {{ resultGenerating ? '생성 중...' : '인터뷰결과생성' }}
        </button>
        <p v-if="!interviewCompleted" class="gp-side-generate-hint">
          모든 질문에 답변을 작성해야 실행됩니다.
        </p>
      </div>
    </aside>
  </div>
</template>

<script lang="ts" setup>
/* [interview-result:start] */
/**
 * @screen: UserList
 * @generatedAt: 2026-04-10T06:55:56.839Z
 * @pipeline: interview-result-v1
 *
 * @keep:
 *  - @id: KEEP-001
 *    @requirement:
 *      - 서버 페이징 처리해 주세요. 응답 스펙은 그대로 해주세요  필터 적용 전 전체 건수로 해주세요.
 *  - @id: KEEP-002
 *    @requirement:
 *      - '전체/사용/미사용' 3상태 선택이 필요 status코드 확장해 주고 코드는 ACTIVE/DORMANT/LOCKED로 지정해 주세요
 *
 */
/* [interview-result:end] */
import { ref, computed, reactive } from 'vue';
import { StandardListTemplate } from '@/components/templates';

const INTERVIEW_RESULT_API = 'http://localhost:4000/api/generate-interview-result';
const answers = ref<string[]>(Array(10).fill(''));
const answerCopied = ref(false);
interface CustomQA { question: string; answer: string; }
const customQAs = ref<CustomQA[]>([]);
const resultGenerating = ref(false);
const resultStatus = ref<'' | 'success' | 'error'>('');
const resultMessage = ref('');
const interviewCompleted = computed(() => answers.value.every(a => a.trim() !== ''));
const INTERVIEW_QUESTIONS = [
  '사용자 목록 조회는 서버 페이징/필터링(권장: GET /api/users)으로 처리할까요, 아니면 전체 데이터를 내려받아 클라이언트에서 필터링할까요? 서버 처리라면 응답 스펙을 {items, total, page, size}로 확정해도 되는지와, total은 \'필터 적용 후 전체 건수\' 기준이 맞는지도 확인 부탁드립니다.',
  '통합검색(keyword)의 검색 대상 필드를 userId/userName/email 3개로 확정할까요, 아니면 전화번호/사번 등 추가 필드도 포함해야 할까요? 또한 매칭 방식은 부분일치(contains/LIKE)로 할지, 시작일치(prefix) 또는 정확일치(equal) 옵션이 필요한지도 결정이 필요합니다(대소문자 구분/공백·특수문자만 입력 시 처리 규칙 포함).',
  '부서 조건은 현재처럼 \'부서명 자유입력 + 부분일치\'로 갈까요, 아니면 조직도/부서코드 기반 선택(드롭다운/자동완성)으로 변경이 필요할까요? 코드 기반이라면 조회 파라미터를 deptId로 받을지, deptPath(상위 포함) 검색이 필요한지도 함께 확인 부탁드립니다.',
  '사용자 목록 Row 스키마를 확정해야 합니다: userId(VARCHAR 길이/허용문자/중복정책), userName(최대길이/필수), email(필수 여부/UNIQUE 여부/형식검증), dept는 deptId FK로 저장할지 deptName을 직접 저장할지, roleCode 길이/코드마스터 연동 여부를 각각 확정해 주실 수 있을까요? 또한 lastLoginDate/createdDate는 DATE로 충분한지, DATETIME(타임존 포함)까지 필요한지도 결정이 필요합니다.',
  '권한(roleCode)은 현재 4종(ADMIN/MANAGER/USER/AUDITOR) 단일값으로 고정할까요, 아니면 향후 한 사용자가 여러 권한을 가질 수 있는 다중권한(매핑 테이블)까지 고려해야 할까요? 다중권한이라면 목록 표시는 \'대표권한 1개\'인지 \'복수 표기\'인지, 검색은 AND/OR 중 어떤 방식인지도 확정이 필요합니다.',
  '사용여부(useYn) 조회 UX를 확정해야 합니다. 현재 체크박스는 \'체크 시 사용중(Y)만\' 의도인데, 미사용(N)만 조회하거나 \'전체/사용/미사용\' 3상태 선택이 필요할까요? 또한 휴면/잠금/퇴사 등 상태가 추가될 가능성이 있다면 useYn 대신 status 코드(예: ACTIVE/DORMANT/LOCKED/RESIGNED)로 확장하는 것이 필요한지 확인 부탁드립니다.',
  '등록일(createdFrom/createdTo) 기준일을 \'계정 생성일(created_at)\'로 볼지, \'최초 승인일/가입완료일\' 등 다른 업무 기준일이 있는지 확정이 필요합니다. 또한 From만/To만 입력을 허용할지, To는 포함(&lt;=) 처리할지(서버에서 23:59:59 보정 여부), 타임존 기준(UTC vs KST)도 함께 결정 부탁드립니다.',
  '목록의 기본 정렬 기준을 무엇으로 할까요(예: created_at DESC, userId ASC 등)? 또한 컬럼 헤더 클릭 정렬(멀티정렬 포함) 요구가 있는지, 정렬이 필요하다면 API 파라미터(sort=createdAt,desc 등) 규격을 어떻게 가져갈지도 확정이 필요합니다.',
  '테이블 행 클릭/사용자ID 클릭 시 \'상세조회/수정\' 화면으로 이동이 필요한가요, 아니면 현 화면은 조회 전용인가요? 이동이 필요하다면 라우팅(/users/{userId}) 및 필요한 추가 API(상세 GET, 수정 PUT/PATCH, 사용여부 토글 PATCH 등) 범위를 어디까지로 할지 결정 부탁드립니다.',
  'API 오류/권한 오류/데이터 없음에 대한 UX 정책을 확정해야 합니다. 예를 들어 401은 로그인 화면으로 이동할지, 403은 \'권한 없음\' 안내만 할지, 5xx/타임아웃은 재시도 버튼 제공 여부와 메시지 문구/로깅(에러코드 노출 여부)을 어떻게 할까요? 또한 조회 중 로딩 표시와 버튼 비활성화(중복요청 방지)도 필요한지 확인 부탁드립니다.',
];
const QUESTION_META = [
  { no: 1, category: '조회조건', question: '사용자 목록 조회는 서버 페이징/필터링(권장: GET /api/users)으로 처리할까요, 아니면 전체 데이터를 내려받아 클라이언트에서 필터링할까요? 서버 처리라면 응답 스펙을 {items, total, page, size}로 확정해도 되는지와, total은 \'필터 적용 후 전체 건수\' 기준이 맞는지도 확인 부탁드립니다.', priority: '높음', tip: '' },
  { no: 2, category: '조회조건', question: '통합검색(keyword)의 검색 대상 필드를 userId/userName/email 3개로 확정할까요, 아니면 전화번호/사번 등 추가 필드도 포함해야 할까요? 또한 매칭 방식은 부분일치(contains/LIKE)로 할지, 시작일치(prefix) 또는 정확일치(equal) 옵션이 필요한지도 결정이 필요합니다(대소문자 구분/공백·특수문자만 입력 시 처리 규칙 포함).', priority: '높음', tip: '' },
  { no: 3, category: '조회조건', question: '부서 조건은 현재처럼 \'부서명 자유입력 + 부분일치\'로 갈까요, 아니면 조직도/부서코드 기반 선택(드롭다운/자동완성)으로 변경이 필요할까요? 코드 기반이라면 조회 파라미터를 deptId로 받을지, deptPath(상위 포함) 검색이 필요한지도 함께 확인 부탁드립니다.', priority: '보통', tip: '' },
  { no: 4, category: '데이터정의', question: '사용자 목록 Row 스키마를 확정해야 합니다: userId(VARCHAR 길이/허용문자/중복정책), userName(최대길이/필수), email(필수 여부/UNIQUE 여부/형식검증), dept는 deptId FK로 저장할지 deptName을 직접 저장할지, roleCode 길이/코드마스터 연동 여부를 각각 확정해 주실 수 있을까요? 또한 lastLoginDate/createdDate는 DATE로 충분한지, DATETIME(타임존 포함)까지 필요한지도 결정이 필요합니다.', priority: '높음', tip: '' },
  { no: 5, category: '조회조건', question: '권한(roleCode)은 현재 4종(ADMIN/MANAGER/USER/AUDITOR) 단일값으로 고정할까요, 아니면 향후 한 사용자가 여러 권한을 가질 수 있는 다중권한(매핑 테이블)까지 고려해야 할까요? 다중권한이라면 목록 표시는 \'대표권한 1개\'인지 \'복수 표기\'인지, 검색은 AND/OR 중 어떤 방식인지도 확정이 필요합니다.', priority: '높음', tip: '' },
  { no: 6, category: '조회조건', question: '사용여부(useYn) 조회 UX를 확정해야 합니다. 현재 체크박스는 \'체크 시 사용중(Y)만\' 의도인데, 미사용(N)만 조회하거나 \'전체/사용/미사용\' 3상태 선택이 필요할까요? 또한 휴면/잠금/퇴사 등 상태가 추가될 가능성이 있다면 useYn 대신 status 코드(예: ACTIVE/DORMANT/LOCKED/RESIGNED)로 확장하는 것이 필요한지 확인 부탁드립니다.', priority: '높음', tip: '' },
  { no: 7, category: '조회조건', question: '등록일(createdFrom/createdTo) 기준일을 \'계정 생성일(created_at)\'로 볼지, \'최초 승인일/가입완료일\' 등 다른 업무 기준일이 있는지 확정이 필요합니다. 또한 From만/To만 입력을 허용할지, To는 포함(&lt;=) 처리할지(서버에서 23:59:59 보정 여부), 타임존 기준(UTC vs KST)도 함께 결정 부탁드립니다.', priority: '보통', tip: '' },
  { no: 8, category: '조회조건', question: '목록의 기본 정렬 기준을 무엇으로 할까요(예: created_at DESC, userId ASC 등)? 또한 컬럼 헤더 클릭 정렬(멀티정렬 포함) 요구가 있는지, 정렬이 필요하다면 API 파라미터(sort=createdAt,desc 등) 규격을 어떻게 가져갈지도 확정이 필요합니다.', priority: '보통', tip: '' },
  { no: 9, category: '사용자행동', question: '테이블 행 클릭/사용자ID 클릭 시 \'상세조회/수정\' 화면으로 이동이 필요한가요, 아니면 현 화면은 조회 전용인가요? 이동이 필요하다면 라우팅(/users/{userId}) 및 필요한 추가 API(상세 GET, 수정 PUT/PATCH, 사용여부 토글 PATCH 등) 범위를 어디까지로 할지 결정 부탁드립니다.', priority: '보통', tip: '' },
  { no: 10, category: '예외처리', question: 'API 오류/권한 오류/데이터 없음에 대한 UX 정책을 확정해야 합니다. 예를 들어 401은 로그인 화면으로 이동할지, 403은 \'권한 없음\' 안내만 할지, 5xx/타임아웃은 재시도 버튼 제공 여부와 메시지 문구/로깅(에러코드 노출 여부)을 어떻게 할까요? 또한 조회 중 로딩 표시와 버튼 비활성화(중복요청 방지)도 필요한지 확인 부탁드립니다.', priority: '높음', tip: '' },
];
function addQA() { customQAs.value.push({ question: '', answer: '' }); }
function removeQA(idx: number) { customQAs.value.splice(idx, 1); }
function copyAnswers() {
  const fixed = INTERVIEW_QUESTIONS.map((q, i) => `Q${i + 1}. ${q}\nA: ${answers.value[i] || '(미작성)'}`).join('\n\n');
  const custom = customQAs.value.length
    ? '\n\n── 현장 추가 질문 ──\n\n' + customQAs.value.map((qa, i) => `추가${i + 1}. ${qa.question || '(질문 없음)'}\nA: ${qa.answer || '(미작성)'}`).join('\n\n')
    : '';
  const text = fixed + custom;
  navigator.clipboard.writeText(text).then(() => {
    answerCopied.value = true; setTimeout(() => { answerCopied.value = false; }, 2000);
  }).catch(() => {
    const el = document.createElement('textarea'); el.value = text;
    document.body.appendChild(el); el.select(); document.execCommand('copy'); document.body.removeChild(el);
    answerCopied.value = true; setTimeout(() => { answerCopied.value = false; }, 2000);
  });
}
async function generateInterviewResult() {
  if (!interviewCompleted.value || resultGenerating.value) return;
  resultGenerating.value = true;
  resultStatus.value = '';
  resultMessage.value = '';
  try {
    const questions = QUESTION_META.map((m, i) => ({ ...m, answer: answers.value[i] ?? '' }));
    const res = await fetch(INTERVIEW_RESULT_API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        screenName: 'UserList',
        pageName:   'UserList',
        title:      '사용자관리',
        pageType:   'list',
        questions,
        customQAs:  customQAs.value,
      }),
    });
    const data = await res.json();
    if (data.success) { resultStatus.value = 'success'; }
    else { resultStatus.value = 'error'; resultMessage.value = data.message ?? '생성에 실패했습니다.'; }
  } catch (e) {
    resultStatus.value = 'error';
    resultMessage.value = `요청 실패: ${(e as Error).message}`;
  } finally {
    resultGenerating.value = false;
  }
}

const PAGE_SIZE = 10;
const page = ref(1);

const search = reactive<Record<string, string | boolean>>({
  keyword: '',
  deptName: '',
  roleCode: '',
  useYn: false,
  createdDateRangeFrom: '',
  createdDateRangeTo: ''
});

const MOCK_DATA: Record<string, string>[] = [
  {
    "userId": "honggildong",
    "userName": "홍길동",
    "deptName": "경영지원팀",
    "email": "hong.gd@company.co.kr",
    "roleCode": "ADMIN",
    "useYn": "Y",
    "lastLoginDate": "2025-03-28",
    "createdDate": "2024-11-12"
  },
  {
    "userId": "kimminsu",
    "userName": "김민수",
    "deptName": "영업1팀",
    "email": "minsu.kim@company.co.kr",
    "roleCode": "MANAGER",
    "useYn": "Y",
    "lastLoginDate": "2025-03-25",
    "createdDate": "2023-08-03"
  },
  {
    "userId": "parkjiyeon",
    "userName": "박지연",
    "deptName": "인사팀",
    "email": "jiyeon.park@company.co.kr",
    "roleCode": "USER",
    "useYn": "Y",
    "lastLoginDate": "2025-03-21",
    "createdDate": "2022-04-19"
  },
  {
    "userId": "leeseungho",
    "userName": "이승호",
    "deptName": "IT운영팀",
    "email": "seungho.lee@company.co.kr",
    "roleCode": "MANAGER",
    "useYn": "Y",
    "lastLoginDate": "2025-03-30",
    "createdDate": "2021-12-07"
  },
  {
    "userId": "choiyuna",
    "userName": "최유나",
    "deptName": "재무회계팀",
    "email": "yuna.choi@company.co.kr",
    "roleCode": "USER",
    "useYn": "Y",
    "lastLoginDate": "2025-03-18",
    "createdDate": "2024-02-14"
  },
  {
    "userId": "jungtaeho",
    "userName": "정태호",
    "deptName": "구매팀",
    "email": "taeho.jung@company.co.kr",
    "roleCode": "USER",
    "useYn": "N",
    "lastLoginDate": "2024-12-22",
    "createdDate": "2020-06-30"
  },
  {
    "userId": "hanseoyeon",
    "userName": "한서연",
    "deptName": "고객지원팀",
    "email": "seoyeon.han@company.co.kr",
    "roleCode": "USER",
    "useYn": "Y",
    "lastLoginDate": "2025-03-27",
    "createdDate": "2023-10-09"
  },
  {
    "userId": "yoonjinho",
    "userName": "윤진호",
    "deptName": "물류관리팀",
    "email": "jinho.yoon@company.co.kr",
    "roleCode": "AUDITOR",
    "useYn": "Y",
    "lastLoginDate": "2025-03-12",
    "createdDate": "2022-09-01"
  },
  {
    "userId": "songhyerin",
    "userName": "송혜린",
    "deptName": "마케팅팀",
    "email": "hyerin.song@company.co.kr",
    "roleCode": "MANAGER",
    "useYn": "Y",
    "lastLoginDate": "2025-03-29",
    "createdDate": "2021-03-16"
  },
  {
    "userId": "ohdoyoung",
    "userName": "오도영",
    "deptName": "품질관리팀",
    "email": "doyoung.oh@company.co.kr",
    "roleCode": "USER",
    "useYn": "N",
    "lastLoginDate": "2024-10-05",
    "createdDate": "2019-05-23"
  }
];

const filteredRows = computed(() =>
  MOCK_DATA.filter(row =>
    (!search.keyword || String(row.keyword ?? '').includes(String(search.keyword))) &&
    (!search.deptName || String(row.deptName ?? '').includes(String(search.deptName))) &&
    (!search.roleCode || String(row.roleCode ?? '').includes(String(search.roleCode))) &&
    (!search.useYn || String(row.useYn ?? '') === 'true') &&
    (!search.createdDateRangeFrom || String(row.createdDateRange ?? '') >= String(search.createdDateRangeFrom)) &&
    (!search.createdDateRangeTo   || String(row.createdDateRange ?? '') <= String(search.createdDateRangeTo))
  ),
);

const totalPages = computed(() =>
  Math.max(1, Math.ceil(filteredRows.value.length / PAGE_SIZE)),
);

const pagedRows = computed(() =>
  filteredRows.value.slice((page.value - 1) * PAGE_SIZE, page.value * PAGE_SIZE),
);

function onSearch() {
  page.value = 1;
}

function onReset() {
  search.keyword = '';
  search.deptName = '';
  search.roleCode = '';
  search.useYn = false;
  search.createdDateRangeFrom = '';
  search.createdDateRangeTo = '';
  page.value = 1;
}
</script>

<style scoped>
.gp-page-title {
  font-size: 18px;
  font-weight: 700;
  color: var(--txt-color-1);
  margin: 0;
}

/* ── 검색 바 ── */
.gp-search-bar {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  gap: 12px;
  padding: 14px 16px;
  background: var(--bg-2);
  border: 1px solid var(--divider-1);
  border-radius: 6px;
}

.gp-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.gp-label {
  font-size: 11px;
  font-weight: 500;
  color: var(--txt-color-3);
}

.gp-search-actions {
  display: flex;
  gap: 6px;
  padding-top: 14px;
}

.gp-field--inline {
  flex-direction: row;
  align-items: center;
  padding-top: 18px;
  gap: 6px;
}

.gp-date-range {
  display: flex;
  align-items: center;
  gap: 6px;
}

.gp-date-sep {
  color: var(--txt-color-3);
  font-size: 13px;
}

.gp-input--date {
  min-width: 120px;
  max-width: 140px;
}

.gp-label--cb {
  padding-top: 0;
  font-size: 13px;
  color: var(--txt-color-1);
  cursor: pointer;
}

.gp-checkbox {
  width: 15px;
  height: 15px;
  cursor: pointer;
  accent-color: var(--brand-secondary-color);
}

.gp-input,
.gp-select {
  height: 32px;
  padding: 0 10px;
  border: 1px solid var(--divider-2);
  border-radius: 4px;
  font-size: 13px;
  background: var(--bg-1);
  color: var(--txt-color-1);
  outline: none;
  min-width: 140px;
}
.gp-input:focus,
.gp-select:focus {
  border-color: var(--brand-secondary-color);
}

/* ── 버튼 ── */
.gp-btn {
  height: 32px;
  padding: 0 14px;
  border-radius: 4px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: 1px solid transparent;
  transition: opacity 0.15s;
}
.gp-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.gp-btn--primary { background: var(--brand-secondary-color); color: #fff; border-color: var(--brand-secondary-color); }
.gp-btn--outline { background: var(--bg-1); border-color: var(--divider-2); color: var(--txt-color-2); }
.gp-btn--danger  { background: #ef4444; color: #fff; border-color: #ef4444; }

/* ── 테이블 ── */
.gp-table-wrap {
  width: 100%;
  height: 100%;
  overflow: auto;
}

.gp-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.gp-th {
  background: var(--bg-2);
  color: var(--txt-color-2);
  font-weight: 600;
  text-align: left;
  padding: 10px 12px;
  border-bottom: 2px solid var(--divider-2);
  white-space: nowrap;
  position: sticky;
  top: 0;
  z-index: 1;
}

.gp-td {
  padding: 9px 12px;
  border-bottom: 1px solid var(--divider-1);
  color: var(--txt-color-1);
}
.gp-td--empty {
  text-align: center;
  color: var(--txt-color-4);
  padding: 48px 0;
}

.gp-tr:hover { background: var(--bg-2); }

/* ── 페이지네이션 ── */
.gp-pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 14px;
  padding: 8px 0;
}

.gp-pagination__info {
  font-size: 13px;
  color: var(--txt-color-3);
}

/* ── 목업 + 인터뷰 질문지 분할 ── */
.gp-page-split {
  display: flex;
  flex: 1;
  min-height: 0;
  width: 100%;
  height: 100%;
  align-items: stretch;
}

.gp-page-split__main {
  flex: 1;
  min-width: 0;
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.gp-page-split__main :deep(.std-list) {
  flex: 1;
  min-height: 0;
}

.gp-page-split__side {
  width: min(360px, 38vw);
  flex-shrink: 0;
  border-left: 1px solid var(--divider-1);
  background: var(--bg-2);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.gp-side-title {
  flex-shrink: 0;
  margin: 0;
  padding: 12px 14px;
  font-size: 13px;
  font-weight: 700;
  color: var(--txt-color-1);
  border-bottom: 1px solid var(--divider-1);
  background: var(--bg-1);
}

.gp-side-list {
  flex: 1;
  margin: 0;
  padding: 10px 12px 14px 28px;
  overflow-y: auto;
  font-size: 12px;
  color: var(--txt-color-2);
  line-height: 1.55;
}

.gp-side-item {
  margin-bottom: 12px;
}

.gp-side-item::marker {
  color: var(--txt-color-4);
  font-weight: 600;
}

.gp-side-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  align-items: center;
  margin-bottom: 4px;
}

.gp-side-cat {
  font-size: 10px;
  padding: 2px 6px;
  border-radius: 4px;
  background: var(--bg-1);
  color: var(--txt-color-3);
  border: 1px solid var(--divider-1);
}

.gp-side-pri {
  font-size: 10px;
  font-weight: 600;
}

.gp-side-pri--high { color: #dc2626; }
.gp-side-pri--mid { color: var(--txt-color-3); }
.gp-side-pri--low { color: var(--txt-color-4); }

.gp-side-q {
  margin: 0 0 6px;
  color: var(--txt-color-1);
  font-size: 12px;
}

/* ── 답변 헤더 ── */
.gp-side-header {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 10px 14px;
  border-bottom: 1px solid var(--divider-1);
  background: var(--bg-1);
}

.gp-side-copy-btn {
  flex-shrink: 0;
  height: 26px;
  padding: 0 10px;
  border-radius: 4px;
  font-size: 11px;
  font-weight: 500;
  cursor: pointer;
  border: 1px solid var(--divider-2);
  background: var(--bg-1);
  color: var(--txt-color-2);
  transition: background 0.15s, color 0.15s;
}

.gp-side-copy-btn:hover { background: var(--bg-2); }
.gp-side-copy-btn--done { background: #f0fdf4; border-color: #bbf7d0; color: #16a34a; }

.gp-side-header-actions {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-shrink: 0;
}

.gp-side-add-btn {
  height: 26px;
  padding: 0 10px;
  border-radius: 4px;
  font-size: 11px;
  font-weight: 600;
  cursor: pointer;
  border: 1px solid var(--brand-secondary-color);
  background: var(--bg-1);
  color: var(--brand-secondary-color);
  transition: background 0.15s, color 0.15s;
  white-space: nowrap;
}

.gp-side-add-btn:hover { background: var(--brand-secondary-color); color: #fff; }

.gp-side-add-btn--ghost {
  height: 32px;
  padding: 0 14px;
  font-size: 12px;
  border-style: dashed;
}

.gp-side-custom { flex-shrink: 0; border-top: 2px dashed var(--divider-1); }

.gp-side-custom-divider {
  font-size: 11px;
  font-weight: 600;
  color: var(--txt-color-3);
  padding: 8px 14px 4px;
  letter-spacing: 0.03em;
}

.gp-side-list--custom { padding-top: 4px; }

.gp-side-item--custom {
  list-style: none;
  padding: 10px 10px 10px 12px;
  border: 1px solid var(--divider-1);
  border-radius: 6px;
  background: var(--bg-1);
  margin-bottom: 10px;
}

.gp-side-custom-q-row {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 6px;
}

.gp-side-custom-q-input {
  flex: 1;
  min-width: 0;
  height: 30px;
  padding: 0 8px;
  border: 1px solid var(--divider-2);
  border-radius: 4px;
  font-size: 12px;
  font-weight: 500;
  color: var(--txt-color-1);
  background: var(--bg-2);
  outline: none;
  transition: border-color 0.15s;
}

.gp-side-custom-q-input:focus { border-color: var(--brand-secondary-color); background: #fff; }
.gp-side-custom-q-input::placeholder { color: var(--txt-color-4); font-weight: 400; }

.gp-side-del-btn {
  flex-shrink: 0;
  width: 24px;
  height: 24px;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: var(--txt-color-4);
  font-size: 11px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.15s, color 0.15s;
}

.gp-side-del-btn:hover { background: #fee2e2; color: #ef4444; }

.gp-side-custom-empty {
  padding: 12px 14px 16px;
  display: flex;
  justify-content: center;
}


/* ── 인터뷰결과생성 영역 ── */
.gp-side-result-area {
  flex-shrink: 0;
  padding: 12px 14px 16px;
  border-top: 2px solid var(--divider-1);
  background: var(--bg-1);
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.gp-side-result-msg { font-size: 11px; line-height: 1.5; padding: 8px 10px; border-radius: 5px; }
.gp-side-result-msg--ok  { background: #f0fdf4; color: #16a34a; border: 1px solid #bbf7d0; }
.gp-side-result-msg--err { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; }
.gp-side-generate-btn {
  width: 100%; height: 36px; border-radius: 6px; font-size: 13px; font-weight: 700;
  cursor: pointer; border: 1.5px solid var(--divider-2); background: var(--bg-2);
  color: var(--txt-color-3); transition: background 0.15s, color 0.15s, border-color 0.15s;
}
.gp-side-generate-btn--ready { border-color: var(--brand-secondary-color); background: var(--brand-secondary-color); color: #fff; }
.gp-side-generate-btn--ready:hover { opacity: 0.9; }
.gp-side-generate-btn:disabled { cursor: not-allowed; opacity: 0.6; }
.gp-side-generate-hint { margin: 0; font-size: 10px; color: var(--txt-color-4); text-align: center; }
/* ── 답변 입력 ── */
.gp-side-answer {
  display: block;
  width: 100%;
  box-sizing: border-box;
  margin-top: 4px;
  padding: 7px 9px;
  border: 1px solid var(--divider-2);
  border-radius: 5px;
  font-size: 12px;
  font-family: inherit;
  line-height: 1.5;
  color: var(--txt-color-1);
  background: var(--bg-1);
  resize: vertical;
  outline: none;
  transition: border-color 0.15s;
}

.gp-side-answer:focus {
  border-color: var(--brand-secondary-color);
  background: #fff;
}

.gp-side-answer::placeholder {
  color: var(--txt-color-4);
  font-style: italic;
}
</style>
