spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tomms}
    username: ${SPRING_DATASOURCE_USERNAME:tomms_user}
    password: ${SPRING_DATASOURCE_PASSWORD:tomms_pass}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath*:biz/**/mybatis/mappers/*.xml
  type-aliases-package: biz
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    biz: DEBUG
    hsc.tomms: DEBUG
    aondev.framework: DEBUG
