<!-- Generated by MockUp Builder | 교육실적관리 (EduProgList) | route: /generated/EduProgList | 2026-04-13T03:09:13.818Z -->
<template>
<!--
  @id: page-split-layout
  @type: container
  @summary: 메인/사이드 분할
  @note: 좌 메인, 우 질문지
  @model: null
  @constraints: null
-->
  <!--
    @id: standard-list-template
    @type: container
    @summary: 리스트 템플릿
    @note: title/search/table/paging
    @model: null
    @constraints: 화면 접근은 준법담당자만 가능, 403/오류 유형별 지정 화면/문구로 처리 (CHG-016, CHG-018)
  -->
  <StandardListTemplate>

    <template #title>
      <!--
        @id: page-title
        @type: display
        @summary: 화면 제목
        @note: 교육실적관리 표시
        @model: null
        @constraints: null
      -->
      <h2 class="gp-page-title">교육실적관리</h2>
    </template>

    <template #search>
      <div class="gp-search-bar">
        <div class="gp-field">
          <label class="gp-label">성명</label>
          <!--
            @id: search-employee-name
            @type: input
            @summary: 성명 검색
            @note: 텍스트로 성명 입력
            @model: search.employeeName
            @constraints: 성명은 코드검색으로 표준값 선택, LIKE 부분일치+초성/공백/대소문자 변형 허용 (CHG-005, CHG-006, TBD-009)
          -->
          <input v-model="search.employeeName" type="text" class="gp-input" placeholder="성명" />
        </div>
        <div class="gp-field">
          <label class="gp-label">부서</label>
          <input v-model="search.departmentName" type="text" class="gp-input" placeholder="부서" />
        </div>
        <div class="gp-field">
          <label class="gp-label">교육일자</label>
          <div class="gp-date-range">
            <input v-model="search.trainingDateRangeFrom" type="date" class="gp-input gp-input--date" />
            <span class="gp-date-sep">~</span>
            <input v-model="search.trainingDateRangeTo" type="date" class="gp-input gp-input--date" />
          </div>
        </div>
        <div class="gp-field">
          <label class="gp-label">참여여부</label>
          <!-- @code_class: YN_CD — 공통코드 그룹 참조. 개발 시 공통코드 API로 옵션을 조회하여 렌더링하세요. -->
          <!--
            @id: search-participation-yn
            @type: input
            @summary: 참여여부 필터
            @note: 공통코드 YN_CD 연동
            @model: search.participationYn
            @constraints: 참여여부는 Y/N 공통코드 기반 필터로 조회 (CHG-003)
          -->
          <select v-model="search.participationYn" class="gp-select">
            <option value="">전체</option>
          </select>
        </div>
        <div class="gp-field">
          <label class="gp-label">합격여부</label>
          <select v-model="search.passYn" class="gp-select">
            <option value="">전체</option>
              <option value="Y">합격</option>
              <option value="N">불합격</option>
          </select>
        </div>
        <div class="gp-search-actions">
          <!--
            @id: search-submit
            @type: action
            @summary: 조회 버튼
            @note: onSearch 실행
            @model: null
            @constraints: 조회 결과 0건 문구는 '조회 결과가 없습니다.'로 고정 (KEEP-001)
          -->
          <button class="gp-btn gp-btn--primary" @click="onSearch">조회</button>
          <button class="gp-btn gp-btn--outline" @click="onReset">초기화</button>
        </div>
      </div>
    </template>

    <template #actions-right>
      <button class="gp-btn gp-btn--primary" @click="() => {}">등록</button>
      <button class="gp-btn gp-btn--outline" @click="() => {}">엑셀 다운로드</button>
      <button class="gp-btn gp-btn--danger"  @click="() => {}">삭제</button>
    </template>

    <template #default>
      <div class="gp-table-wrap">
        <!--
          @id: training-result-table
          @type: display
          @summary: 교육실적 목록
          @note: pagedRows로 행 렌더링
          @model: null
          @constraints: 기본정렬 employeeNo ASC, 사용자 다중정렬 지원; 부서는 교육일자 기준 소속 적용 (CHG-010, ADD-001, CHG-017)
        -->
        <table class="gp-table">
          <thead>
            <tr>
              <th class="gp-th" style="width:50px">No</th>
              <th class="gp-th">사번</th>
              <th class="gp-th">성명</th>
              <th class="gp-th">부서</th>
              <th class="gp-th">교육과정</th>
              <th class="gp-th">교육일자</th>
              <th class="gp-th">참여</th>
              <th class="gp-th">시험점수</th>
              <th class="gp-th">합격</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="!pagedRows.length">
              <td :colspan="9" class="gp-td gp-td--empty">조회 결과가 없습니다.</td>
            </tr>
            <tr v-for="(row, i) in pagedRows" :key="i" class="gp-tr">
              <td class="gp-td">{{ (page - 1) * PAGE_SIZE + i + 1 }}</td>
              <td class="gp-td">{{ row.employeeNo }}</td>
              <td class="gp-td">{{ row.employeeName }}</td>
              <td class="gp-td">{{ row.departmentName }}</td>
              <td class="gp-td">{{ row.trainingTitle }}</td>
              <td class="gp-td">{{ row.trainingDate }}</td>
              <td class="gp-td">{{ row.participationYn }}</td>
              <td class="gp-td">{{ row.examScore }}</td>
              <td class="gp-td">{{ row.passYn }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>

    <template #pagination>
      <div class="gp-pagination">
        <button class="gp-btn gp-btn--outline" :disabled="page <= 1" @click="page--">이전</button>
        <span class="gp-pagination__info">{{ page }} / {{ totalPages }} (총 {{ filteredRows.length }}건)</span>
        <button class="gp-btn gp-btn--outline" :disabled="page >= totalPages" @click="page++">다음</button>
      </div>
    </template>

  </StandardListTemplate>

</template>

<script lang="ts" setup>
/* [interview-result:start] */
/**
 * @screen: EduProgList
 * @generatedAt: 2026-04-13T03:16:19.112Z
 * @pipeline: interview-result-v1
 *
 * @keep:
 *  - @id: KEEP-001
 *    @requirement:
 *      - 조회 결과 0건 메시지는 현재처럼 '조회 결과가 없습니다.'로 고정한다.
 *
 * @change:
 *  - @id: CHG-001
 *    @requirement:
 *      - eduResultId 단일키를 생성하여 Primary Key로 사용
 *  - @id: CHG-002
 *    @requirement:
 *      - 교육과정+사번 기준으로 중복 여부 체크
 *  - @id: CHG-003
 *    @requirement:
 *      - 사번 varchar(50), 성명 varchar(100), 부서명 varchar(100), 교육과정명 varchar(500), 시험점수 정수(0~100), 참여여부 Y/N, 합격여부 Y/N
 *  - @id: CHG-004
 *    @requirement:
 *      - 과정코드와 연계하며 과정ID/과정코드/버전(개정) 관리, 조회 표시는 당시 명칭 기준
 *  - @id: CHG-005
 *    @requirement:
 *      - 성명은 부분일치 검색 + 대소문자/공백/초성 검색 지원
 *  - @id: CHG-006
 *    @requirement:
 *      - 성명/부서는 코드 검색으로 진행
 *  - @id: CHG-007
 *    @requirement:
 *      - from/to 포함(>= from, <= to)으로 확정
 *  - @id: CHG-008
 *    @requirement:
 *      - 저장타입은 DATETIME
 *  - @id: CHG-009
 *    @requirement:
 *      - 기본은 KST, 향후 locale에 따라 시간대 변경 가능해야 함
 *  - @id: CHG-010
 *    @requirement:
 *      - 사번 오름차순 기본 정렬
 *  - @id: CHG-011
 *    @requirement:
 *      - 등록 버튼은 엑셀 업로드 일괄등록으로 처리
 *  - @id: CHG-012
 *    @requirement:
 *      - 필수: 사번, 교육과정, 교육일자, 참여여부, 시험점수. 동일키 중복 시 차단
 *  - @id: CHG-013
 *    @requirement:
 *      - 체크박스 다건 삭제 + 물리삭제
 *  - @id: CHG-014
 *    @requirement:
 *      - 삭제 전 확인 팝업 제공
 *  - @id: CHG-015
 *    @requirement:
 *      - 교육과정이 활성화된 건만 삭제 가능
 *  - @id: CHG-016
 *    @requirement:
 *      - 준법담당자만 화면 접근 가능, 준법담당자는 등록/삭제/엑셀다운로드 가능
 *  - @id: CHG-017
 *    @requirement:
 *      - 교육 당시 소속된 부서 기준 적용
 *  - @id: CHG-018
 *    @requirement:
 *      - 403은 접근 차단 페이지, 5xx/네트워크 오류는 오류페이지 이동, 엑셀 다운로드 실패 시 안내 문구 표시
 *
 * @add:
 *  - @id: ADD-001
 *    @requirement:
 *      - 사용자가 다중 정렬(1차/2차 등)이 가능하도록 목록 정렬 기능을 제공한다.
 *
 * @tbd:
 *  - @id: TBD-001
 *    @reason: 답변에 '부서명 varchaa 100'로 표기되어 있어 varchar(100)인지 확인 필요
 *  - @id: TBD-002
 *    @reason: from/to 중 한쪽만 입력 시 허용 여부가 답변에 없음
 *  - @id: TBD-003
 *    @reason: to 날짜 입력 시 23:59:59 포함 등 경계값 처리 규칙이 미정
 *  - @id: TBD-004
 *    @reason: 미참여일 때 시험점수/합격여부를 NULL로 둘지 0/N으로 둘지 규칙이 미정
 *  - @id: TBD-005
 *    @reason: 필수항목에 시험점수가 포함되어 있으나 미참여 시 입력/저장 규칙이 미정
 *  - @id: TBD-006
 *    @reason: Q1은 교육과정+사번 중복체크, Q7은 '동일키' 중복 차단이라 했으나 동일키가 (사번+과정)인지 (사번+과정+일자)인지 확정 필요
 *  - @id: TBD-007
 *    @reason: 과정이 차수별로 신규 생성 예정이라 했으나, 재교육/재시험 시 동일 과정 판정 기준(차수 포함 여부) 확인 필요
 *  - @id: TBD-008
 *    @reason: 당시명칭 표시를 위해 실적에 명칭 스냅샷을 저장할지, 과정 버전 이력으로 재현할지 구현 방식 결정 필요
 *  - @id: TBD-009
 *    @reason: 성명은 부분일치+초성 지원이면서 성명/부서는 코드검색이라 하여 입력 방식(자동완성/검색팝업/자유입력 병행) 확정 필요
 *  - @id: TBD-010
 *    @reason: '교육과정이 활성화'의 기준 시점(현재 활성/당시 활성) 및 활성 상태 값 정의가 필요
 *  - @id: TBD-011
 *    @reason: 엑셀 업로드 컬럼 매핑, 오류 행 처리(부분 성공/전체 롤백), 오류 다운로드 제공 여부가 미정
 *  - @id: TBD-012
 *    @reason: 준법담당자 가능은 확정이나 다운로드 데이터 범위(전체/필터 반영) 및 포맷이 미정
 *
 */
/* [interview-result:end] */
import { ref, computed, reactive } from 'vue';
import { StandardListTemplate } from '@/components/templates';

const PAGE_SIZE = 10;
const page = ref(1);

const search = reactive<Record<string, string | boolean>>({
  employeeName: '',
  departmentName: '',
  trainingDateRangeFrom: '',
  trainingDateRangeTo: '',
  participationYn: '',
  passYn: ''
});

const MOCK_DATA: Record<string, string>[] = [
  {
    "employeeNo": "20210045",
    "employeeName": "김민준",
    "departmentName": "준법감시팀",
    "trainingTitle": "2025년 상반기 준법교육(필수)",
    "trainingDate": "2025-01-15",
    "participationYn": "Y",
    "examScore": "92.5",
    "passYn": "Y"
  },
  {
    "employeeNo": "20190312",
    "employeeName": "이서연",
    "departmentName": "인사팀",
    "trainingTitle": "개인정보보호 및 정보보안 교육",
    "trainingDate": "2025-02-03",
    "participationYn": "Y",
    "examScore": "78.0",
    "passYn": "Y"
  },
  {
    "employeeNo": "20220487",
    "employeeName": "박지훈",
    "departmentName": "영업1팀",
    "trainingTitle": "자금세탁방지(AML) 기본교육",
    "trainingDate": "2025-02-18",
    "participationYn": "Y",
    "examScore": "64.5",
    "passYn": "N"
  },
  {
    "employeeNo": "20180566",
    "employeeName": "최유진",
    "departmentName": "재무팀",
    "trainingTitle": "공정거래 및 하도급 준수 교육",
    "trainingDate": "2025-03-05",
    "participationYn": "N",
    "examScore": "0.0",
    "passYn": "N"
  },
  {
    "employeeNo": "20200991",
    "employeeName": "정현우",
    "departmentName": "IT보안팀",
    "trainingTitle": "정보보안 사고 대응 및 보고 절차",
    "trainingDate": "2025-03-12",
    "participationYn": "Y",
    "examScore": "88.0",
    "passYn": "Y"
  },
  {
    "employeeNo": "20170234",
    "employeeName": "한지민",
    "departmentName": "구매팀",
    "trainingTitle": "부패방지 및 청렴교육",
    "trainingDate": "2025-03-20",
    "participationYn": "Y",
    "examScore": "71.5",
    "passYn": "Y"
  },
  {
    "employeeNo": "20230118",
    "employeeName": "오세훈",
    "departmentName": "품질관리팀",
    "trainingTitle": "내부통제 및 윤리규정 이해",
    "trainingDate": "2025-04-02",
    "participationYn": "N",
    "examScore": "0.0",
    "passYn": "N"
  },
  {
    "employeeNo": "20160678",
    "employeeName": "윤아름",
    "departmentName": "고객지원팀",
    "trainingTitle": "민원응대 시 준법 유의사항",
    "trainingDate": "2025-04-10",
    "participationYn": "Y",
    "examScore": "59.0",
    "passYn": "N"
  },
  {
    "employeeNo": "20211007",
    "employeeName": "장도윤",
    "departmentName": "리스크관리팀",
    "trainingTitle": "리스크관리와 준법감시 협업 프로세스",
    "trainingDate": "2025-04-22",
    "participationYn": "Y",
    "examScore": "83.5",
    "passYn": "Y"
  },
  {
    "employeeNo": "20191245",
    "employeeName": "신예은",
    "departmentName": "마케팅팀",
    "trainingTitle": "광고·표시 준수 및 소비자보호 교육",
    "trainingDate": "2025-05-06",
    "participationYn": "Y",
    "examScore": "76.0",
    "passYn": "Y"
  }
];

const filteredRows = computed(() =>
  MOCK_DATA.filter(row =>
    (!search.employeeName || String(row.employeeName ?? '').includes(String(search.employeeName))) &&
    (!search.departmentName || String(row.departmentName ?? '').includes(String(search.departmentName))) &&
    (!search.trainingDateRangeFrom || String(row.trainingDateRange ?? '') >= String(search.trainingDateRangeFrom)) &&
    (!search.trainingDateRangeTo   || String(row.trainingDateRange ?? '') <= String(search.trainingDateRangeTo)) &&
    (!search.participationYn || String(row.participationYn ?? '').includes(String(search.participationYn))) &&
    (!search.passYn || String(row.passYn ?? '').includes(String(search.passYn)))
  ),
);

const totalPages = computed(() =>
  Math.max(1, Math.ceil(filteredRows.value.length / PAGE_SIZE)),
);

const pagedRows = computed(() =>
  filteredRows.value.slice((page.value - 1) * PAGE_SIZE, page.value * PAGE_SIZE),
);

function onSearch() {
  page.value = 1;
}

function onReset() {
  search.employeeName = '';
  search.departmentName = '';
  search.trainingDateRangeFrom = '';
  search.trainingDateRangeTo = '';
  search.participationYn = '';
  search.passYn = '';
  page.value = 1;
}
</script>

<style scoped>
.gp-page-title {
  font-size: 18px;
  font-weight: 700;
  color: var(--txt-color-1);
  margin: 0;
}

/* ── 검색 바 ── */
.gp-search-bar {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  gap: 12px;
  padding: 14px 16px;
  background: var(--bg-2);
  border: 1px solid var(--divider-1);
  border-radius: 6px;
}

.gp-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.gp-label {
  font-size: 11px;
  font-weight: 500;
  color: var(--txt-color-3);
}

.gp-search-actions {
  display: flex;
  gap: 6px;
  padding-top: 14px;
}

.gp-field--inline {
  flex-direction: row;
  align-items: center;
  padding-top: 18px;
  gap: 6px;
}

.gp-date-range {
  display: flex;
  align-items: center;
  gap: 6px;
}

.gp-date-sep {
  color: var(--txt-color-3);
  font-size: 13px;
}

.gp-input--date {
  min-width: 120px;
  max-width: 140px;
}

.gp-label--cb {
  padding-top: 0;
  font-size: 13px;
  color: var(--txt-color-1);
  cursor: pointer;
}

.gp-checkbox {
  width: 15px;
  height: 15px;
  cursor: pointer;
  accent-color: var(--brand-secondary-color);
}

.gp-input,
.gp-select {
  height: 32px;
  padding: 0 10px;
  border: 1px solid var(--divider-2);
  border-radius: 4px;
  font-size: 13px;
  background: var(--bg-1);
  color: var(--txt-color-1);
  outline: none;
  min-width: 140px;
}
.gp-input:focus,
.gp-select:focus {
  border-color: var(--brand-secondary-color);
}

/* ── 버튼 ── */
.gp-btn {
  height: 32px;
  padding: 0 14px;
  border-radius: 4px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: 1px solid transparent;
  transition: opacity 0.15s;
}
.gp-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.gp-btn--primary { background: var(--brand-secondary-color); color: #fff; border-color: var(--brand-secondary-color); }
.gp-btn--outline { background: var(--bg-1); border-color: var(--divider-2); color: var(--txt-color-2); }
.gp-btn--danger  { background: #ef4444; color: #fff; border-color: #ef4444; }

/* ── 테이블 ── */
.gp-table-wrap {
  width: 100%;
  height: 100%;
  overflow: auto;
}

.gp-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.gp-th {
  background: var(--bg-2);
  color: var(--txt-color-2);
  font-weight: 600;
  text-align: left;
  padding: 10px 12px;
  border-bottom: 2px solid var(--divider-2);
  white-space: nowrap;
  position: sticky;
  top: 0;
  z-index: 1;
}

.gp-td {
  padding: 9px 12px;
  border-bottom: 1px solid var(--divider-1);
  color: var(--txt-color-1);
}
.gp-td--empty {
  text-align: center;
  color: var(--txt-color-4);
  padding: 48px 0;
}

.gp-tr:hover { background: var(--bg-2); }

/* ── 페이지네이션 ── */
.gp-pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 14px;
  padding: 8px 0;
}

.gp-pagination__info {
  font-size: 13px;
  color: var(--txt-color-3);
}

</style>
